package com.extollit.gaming.ai.path.model;

/**
 * A filter for influencing the passibility of nodes computed for the A* graph.
 */
public interface IGraphNodeFilter {
    /**
     * When a node has been computed by the engine (and underlying algorithm depending on the pathing entity's
     * capabilities) this method can be called allowing some control and influence over the passibility of nodes.
     * The returned passibility is used to determine the new passibility for the node.
     *
     * Since nodes are cached this method is typically called only once per set of coordinates until cache invalidation
     * occurs.
     *
     * @param node the node that was generated by the engine, contains read-only information about the node
     * @return new passibility for the node passed in or null to leave the node as is.
     */
    Passibility mapPassibility(INode node);
}
