package com.extollit.gaming.ai.path.model;

/**
 * A plug-in for altering paths generated by the engine
 */
public interface IPathProcessor {
    /**
     * Once a valid path has been generated by the engine for use with a pathing entity, this method is called
     * by the engine allowing the caller opportunity to modify the path before it is used and bound to the engine.
     *
     * @param path the newly generated path (not yet bound to the engine)
     */
    void processPath(IPath path);
}
